### ISSUE TITLE
How do I find the prefix?

### ISSUE THREAD

**Issue by spank8857** [TheRealToxicDev/Toxic-Security#2]
I am currently in a server where I am the staff taking care of most of the stuff, I have a drama with someone else and they are refusing to give me the prefix for the bot. 701125590308356167 is the guild ID. How do I find the prefix?

**Comment by CodeMeAPixel** [comment]
@spank8857 The bots internal (unchangeable) prefix is a @Mention 👌 @Skynet help should show you the guild prefix 😉

![image](https://user-images.githubusercontent.com/59587139/90991848-64947880-e569-11ea-931d-8c8b507a1556.jpeg)
